spring:
  datasource:
    url: jdbc:mysql://${db.address}:${db.port}/${db.name}?allowPublicKeyRetrieval=true&serverTimezone=UTC&useSSL=false
    username: ${db.username}
    password: ${db.password}

# Below are custom application YML settings

elasticsearch:
  domain: ${es.domain}
  port: ${es.port}
  scheme: ${es.scheme}
  connect-timeout: 5000 # 5 secs
  socket-timeout: 300000 # 300 secs / 5 mins
